#!/bin/sh
#================================================================
# btb-phylo
#================================================================

RESULTS=$1
CONFIG=$2
THREADS=$3
DOCKER=${4:-foo}

if [ $DOCKER = "--with-docker" ]; then
    #docker build -t btb-phylo:latest .
    docker run --rm --mount type=bind,source=$RESULTS,target=/results btb-phylo:latest /results $CONFIG $THREADS
elif [ $DOCKER = "foo" ]; then
    python update_summary.py --summary_bucket s3-staging-area --summary_key nickpestell/btb_wgs_samples.csv
    python btb_phylo.py $RESULTS --summary_bucket s3-staging-area --summary_key nickpestell/btb_wgs_samples.csv -j $THREADS --config $CONFIG 
else
    echo "unrecognised argument: if running with docker, use '--with-docker'"
fi