#!/bin/sh
#================================================================
# btb-phylo
#================================================================

RESULTS=$1
CONSENSUS=$2
CONFIG=$3
THREADS=$4
if $THREADS
    DOCKER=${5:-no-docker}

if [ $DOCKER = "--with-docker" ]; then
    echo "Running btb-phylo with docker"
    docker pull aphacsubot/btb-phylo:dockerize
    docker run --rm -it --mount type=bind,source=$RESULTS,target=/results --mount type=bind,source=$CONSENSUS,target=/consensus --mount type=bind,source=$CONFIG,target=/config.json aphacsubot/btb-phylo:dockerize /results /consensus /config.json $THREADS
elif [ $DOCKER = "no-docker" ]; then
    python update_summary.py --summary_bucket s3-staging-area --summary_key nickpestell/btb_wgs_samples.csv
    python btb_phylo.py $RESULTS $CONSENSUS --summary_bucket s3-staging-area --summary_key nickpestell/btb_wgs_samples.csv -j $THREADS --config $CONFIG 
else
    echo "unrecognised argument: if running with docker, use '--with-docker'"
fi