version: 2.1

commands:
  build-and-push:
    parameters:
      tag:
        description: Tag to push built docker image to
        type: string

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=<< parameters.tag >>
          docker build -t aphacsubot/btb-phylo:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aphacsubot/btb-phylo:$TAG

jobs:
  # Docker image containing phylo pipeline $CIRCLE_BRANCH
  build:
    docker:
      # Circleci base ubuntu image
      - image: &build_img ubuntu-2204:2022.04.1

    steps:
      - build-and-push:
          tag: $CIRCLE_BRANCH

  deploy: 
    docker:
      # Circleci base ubuntu image
      - image: *build_img

    steps:
      - build-and-push:
          tag: latest

  unittests:
    executor: phylo-pipeline
    steps:
      - run: |
          cd /btb-phylo/
          python unit_tests.py

executors:
  phylo-pipeline:
    docker:
      - image: "aphacsubot/btb-phylo:$CIRCLE_BRANCH"

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build

      - unittests:
          requires:
            - build

      - deploy:
          requires:
            - build
            - unittests
          filters:
            branches:
              only: main
