version: 2.1

commands:
  build-and-push:
    parameters:
      tag:
        description: Tag to push built docker image to
        type: string

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=<< parameters.tag >>
          docker build -t aphacsubot/btb-phylo:$TAG -f ./docker/Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aphacsubot/btb-phylo:$TAG

jobs:
  # Docker image containing phylo pipeline $CIRCLE_BRANCH
  build:
    docker:
      # Circleci base ubuntu image
      - image: &build_img cimg/base:2020.01

    steps:
      - build-and-push:
          tag: $CIRCLE_BRANCH

  unittests:
    executor: phylo-pipeline
    steps:
      - run: |
          cd /BovTB-nf/
          python unit_tests.py

executors:
  phylo-pipeline:
    docker:
      - image: "aphacsubot/btb-phylo:$CIRCLE_BRANCH"

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build

      - unittests:
          requires:
            - build
